### ISSUE TITLE
XmlPrettyPrint needs a case for Xml.ProcessingInstruction

### ISSUE THREAD

**Issue by AdrianV** [TomByrne/xml-tools#1]
Haxe switch exhaustiveness check needs a case for every possibilty

**Comment by TomByrne** [comment]
Which switch are you talking about?
The one in printNode() has a case for Xml.ProcessingInstruction on line 62.
It seems to build fine for me in 3.2

**Comment by AdrianV** [comment]
sorry but there is no case for Xml.ProcessingInstruction, but a case for Xml.Prolog which has been changed sometime ago.

**Comment by TomByrne** [comment]
Sorry, seems like haxelib had an old version.
Can you try again with v1.1 and let me know if there are any issues.

**Comment by AdrianV** [comment]
it compiles know for me, but I think the whitepsace on line 84 for Xml.ProcessingInstruction in "<? " is wrong because it will produce "<? xml...." and not "<?xml..."

**Comment by TomByrne** [comment]
Thanks, I've added a test for this now and all is working.
